name: chat
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.15.1
  firebase_auth: ^4.7.2
  cloud_firestore: ^4.8.6
  image_picker: ^1.1.1
  firebase_storage: ^11.5.6
  intl: ^0.19.0
  firebase_messaging: ^14.6.5
  flutter_local_notifications: ^17.0.1
  shared_preferences: ^2.2.2
  http: ^1.3.0
  googleapis_auth: ^1.4.1
  firebase_analytics: ^10.7.4
  audioplayers: ^5.2.1
  google_fonts: ^6.1.0
  animated_splash_screen: ^1.3.0
  lottie: ^3.1.0
  async: ^2.11.0
  provider: ^6.1.1
  permission_handler: ^11.0.1
  url_launcher: ^6.2.0
  rxdart: ^0.27.7
  flutter_dotenv: ^5.1.0

flutter_native_splash:
  image : images/chat.jpg
  color : "#FFFFFF"

flutter_icons:
  android: true
  ios: true
  image_path: "images/chat.jpg"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/
