name: chat
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.1
  image_picker: ^1.1.1
  firebase_storage: ^12.4.4
  intl: ^0.19.0
  firebase_messaging: ^15.0.1
  flutter_local_notifications: ^17.0.1
  shared_preferences: ^2.2.2
  http: ^1.3.0
  googleapis_auth: ^1.4.1
  firebase_analytics: ^11.4.4
  audioplayers: ^5.2.1
  google_fonts: ^6.1.0
  animated_splash_screen: ^1.3.0
  lottie: ^3.1.0

flutter_native_splash:
  image : images/chat.jpg
  color : "#FFFFFF"

flutter_icons:
  android: true
  ios: true
  image_path: "images/chat.jpg"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  
  assets:
    - images/
    - assets/audio/
    - assets/fonts/

  fonts:
    - family: PressStart2P
      fonts:
        - asset: assets/fonts/PressStart2P-Regular.ttf
    - family: VT323
      fonts:
        - asset: assets/fonts/VT323-Regular.ttf
