// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNeaFJl7vrmvuhAXaWPZmnySlJaxqQMco',
    appId: '1:564540232720:web:c25b93aa3cbda0f82aa695',
    messagingSenderId: '564540232720',
    projectId: 'chat-a9a04',
    authDomain: 'chat-a9a04.firebaseapp.com',
    storageBucket: 'chat-a9a04.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqB5n8F3ceunS3Dyri0d4d5hp8OVeu9ew',
    appId: '1:564540232720:android:b6bcc5d56f95b4ec2aa695',
    messagingSenderId: '564540232720',
    projectId: 'chat-a9a04',
    storageBucket: 'chat-a9a04.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmug96j2RiPN4_pRAaPB-3dHOYcIkAUwE',
    appId: '1:564540232720:ios:a5b4b46a64ec8aca2aa695',
    messagingSenderId: '564540232720',
    projectId: 'chat-a9a04',
    storageBucket: 'chat-a9a04.appspot.com',
    iosBundleId: 'com.example.chat',
  );
}
